import fs from 'fs-extra';
import path from 'path';
import { AgentSessionState, Message, SessionMeta, KnowledgeChunk } from '../../../types';
import { SESSIONS_DIR } from '../../config';
import { v4 as uuidv4 } from 'uuid';

// Ensure sessions directory exists
fs.ensureDirSync(SESSIONS_DIR);

const STORAGE_KEY_ACTIVE = 'active_session_id';
const ACTIVE_SESSION_FILE = path.join(SESSIONS_DIR, 'active.txt');

export const sessionService = {
  createSession: async (): Promise<string> => {
    const sessionId = `sess_${Date.now().toString(36)}${Math.random().toString(36).substr(2, 5)}`;
    const initialState: AgentSessionState = {
      sessionId,
      title: '新会话',
      geminiHistory: [],
      uiMessages: [],
      vfs: {
        'README.md': {
            path: 'README.md',
            content: '# Enterprise Agentic Project\n\nGenerated by Gemini 3 Supervisor.',
            language: 'markdown'
        }
      },
      knowledgeChunks: [],
      lastUpdated: Date.now()
    };
    
    await sessionService.saveSession(sessionId, initialState);
    await sessionService.setActiveSession(sessionId);
    return sessionId;
  },

  getSession: async (sessionId: string): Promise<AgentSessionState | null> => {
    const filePath = path.join(SESSIONS_DIR, `${sessionId}.json`);
    if (!await fs.pathExists(filePath)) return null;
    try {
      return await fs.readJson(filePath);
    } catch {
      return null;
    }
  },

  saveSession: async (sessionId: string, state: AgentSessionState): Promise<void> => {
    const filePath = path.join(SESSIONS_DIR, `${sessionId}.json`);
    await fs.writeJson(filePath, state, { spaces: 2 });
  },

  updateSession: async (sessionId: string, updates: Partial<AgentSessionState>): Promise<void> => {
    const current = await sessionService.getSession(sessionId);
    if (!current) return;
    const newState = { ...current, ...updates, lastUpdated: Date.now() };
    await sessionService.saveSession(sessionId, newState);
  },

  updateMessage: async (sessionId: string, messageId: string, updates: Partial<Message>): Promise<void> => {
    const current = await sessionService.getSession(sessionId);
    if (!current) return;
    const msgIndex = current.uiMessages.findIndex(m => m.id === messageId);
    if (msgIndex === -1) {
        // If not found, it might be a new assistant message, we should handle that
        // in chatController by explicitly adding it first.
        return;
    }
    current.uiMessages[msgIndex] = { ...current.uiMessages[msgIndex], ...updates };
    current.lastUpdated = Date.now();
    await sessionService.saveSession(sessionId, current);
  },

  listSessions: async (): Promise<SessionMeta[]> => {
    const files = await fs.readdir(SESSIONS_DIR);
    const sessions: SessionMeta[] = [];
    
    for (const file of files) {
      if (!file.endsWith('.json')) continue;
      try {
        const data = await fs.readJson(path.join(SESSIONS_DIR, file));
        if (data.sessionId) {
          sessions.push({
            sessionId: data.sessionId,
            title: data.title || '新会话',
            lastUpdated: data.lastUpdated || 0
          });
        }
      } catch {}
    }
    return sessions.sort((a, b) => b.lastUpdated - a.lastUpdated);
  },

  setActiveSession: async (sessionId: string): Promise<void> => {
    await fs.writeFile(ACTIVE_SESSION_FILE, sessionId);
  },

  getActiveSessionId: async (): Promise<string | null> => {
    if (!await fs.pathExists(ACTIVE_SESSION_FILE)) return null;
    return (await fs.readFile(ACTIVE_SESSION_FILE, 'utf-8')).trim();
  },

  deleteSession: async (sessionId: string): Promise<void> => {
    await fs.remove(path.join(SESSIONS_DIR, `${sessionId}.json`));
    const active = await sessionService.getActiveSessionId();
    if (active === sessionId) {
       await fs.remove(ACTIVE_SESSION_FILE);
    }
  },
  
  clearSessionContent: async (sessionId: string): Promise<void> => {
      const initialState: AgentSessionState = {
        sessionId,
        title: '新会话',
        geminiHistory: [],
        uiMessages: [],
        vfs: {
          'README.md': {
              path: 'README.md',
              content: '# Enterprise Agentic Project\n\nGenerated by Gemini 3 Supervisor.',
              language: 'markdown'
          }
        },
        knowledgeChunks: [],
        lastUpdated: Date.now()
      };
      await sessionService.saveSession(sessionId, initialState);
  }
};
