
import { Message, VfsFile } from "../types";

export interface AgentSessionState {
  sessionId: string;
  geminiHistory: any[]; 
  uiMessages: Message[]; 
  vfs: Record<string, VfsFile>;
  lastUpdated: number;
}

const STORAGE_KEY_ACTIVE = 'agent_session_active';
const STORAGE_PREFIX = 'agent_session_data_';

export const agentStateService = {
  initializeSession: (): string => {
    let activeId = localStorage.getItem(STORAGE_KEY_ACTIVE);
    if (!activeId) {
      activeId = agentStateService.createSession();
    }
    return activeId;
  },

  createSession: (): string => {
    const newId = 'sess_' + Date.now().toString(36) + Math.random().toString(36).substr(2, 5);
    localStorage.setItem(STORAGE_KEY_ACTIVE, newId);
    
    const initialState: AgentSessionState = {
      sessionId: newId,
      geminiHistory: [],
      uiMessages: [],
      vfs: {
        'README.md': { 
          path: 'README.md', 
          content: '# Enterprise Agentic Project\n\nGenerated by Gemini 3 Supervisor.', 
          language: 'markdown' 
        }
      },
      lastUpdated: Date.now()
    };
    
    localStorage.setItem(STORAGE_PREFIX + newId, JSON.stringify(initialState));
    return newId;
  },

  getSession: (sessionId: string): AgentSessionState | null => {
    const raw = localStorage.getItem(STORAGE_PREFIX + sessionId);
    if (!raw) return null;
    try {
      return JSON.parse(raw);
    } catch (e) {
      return null;
    }
  },

  saveSession: (sessionId: string, updates: Partial<AgentSessionState>) => {
    const current = agentStateService.getSession(sessionId);
    if (!current) return;
    const updatedState = { ...current, ...updates, lastUpdated: Date.now() };
    localStorage.setItem(STORAGE_PREFIX + sessionId, JSON.stringify(updatedState));
  },

  clearSession: (sessionId: string) => {
    localStorage.removeItem(STORAGE_PREFIX + sessionId);
    localStorage.removeItem(STORAGE_KEY_ACTIVE);
  },

  updateVfs: (sessionId: string, path: string, content: string, language: string) => {
    const session = agentStateService.getSession(sessionId);
    if (!session) return;
    const newVfs = { ...session.vfs, [path]: { path, content, language } };
    agentStateService.saveSession(sessionId, { vfs: newVfs });
    window.dispatchEvent(new CustomEvent('vfs-updated', { detail: newVfs }));
  },

  clearSessionContext: (sessionId: string) => {
    const current = agentStateService.getSession(sessionId);
    if (!current || !current.geminiHistory) return;
    const cleanHistory = current.geminiHistory.map((msg: any) => {
      if (!msg.parts) return null;
      const textParts = msg.parts.filter((p: any) => p.text);
      if (textParts.length === 0) return null;
      return { role: msg.role, parts: textParts };
    }).filter(Boolean);
    agentStateService.saveSession(sessionId, { geminiHistory: cleanHistory });
  },

  syncUiState: (sessionId: string, messages: Message[]) => {
      agentStateService.saveSession(sessionId, { uiMessages: messages });
  }
};
