import { Message, VfsFile } from "../types";

/** 语义分块结构，与 ChunkCard 的 SemanticChunk 一致 */
export interface KnowledgeChunk {
  content: string;
  summary: string;
  boundaryReason: string;
}

export interface AgentSessionState {
  sessionId: string;
  /** 会话标题，默认由首条用户消息生成 */
  title?: string;
  geminiHistory: any[];
  uiMessages: Message[];
  vfs: Record<string, VfsFile>;
  /** 知识库分块，供 search_knowledge 检索 */
  knowledgeChunks?: KnowledgeChunk[];
  lastUpdated: number;
}

export interface SessionMeta {
  sessionId: string;
  title: string;
  lastUpdated: number;
}

const STORAGE_KEY_ACTIVE = 'agent_session_active';
const STORAGE_PREFIX = 'agent_session_data_';

export const agentStateService = {
  initializeSession: (): string => {
    let activeId = localStorage.getItem(STORAGE_KEY_ACTIVE);
    if (!activeId) {
      activeId = agentStateService.createSession();
    }
    return activeId;
  },

  createSession: (): string => {
    const newId = 'sess_' + Date.now().toString(36) + Math.random().toString(36).substr(2, 5);
    localStorage.setItem(STORAGE_KEY_ACTIVE, newId);

    const initialState: AgentSessionState = {
      sessionId: newId,
      title: '新会话',
      geminiHistory: [],
      uiMessages: [],
      vfs: {
        'README.md': {
          path: 'README.md',
          content: '# Enterprise Agentic Project\n\nGenerated by Gemini 3 Supervisor.',
          language: 'markdown'
        }
      },
      knowledgeChunks: [],
      lastUpdated: Date.now()
    };

    localStorage.setItem(STORAGE_PREFIX + newId, JSON.stringify(initialState));
    return newId;
  },

  /** 列出所有会话（按最后更新时间倒序） */
  listSessions: (): SessionMeta[] => {
    const keys = Object.keys(localStorage).filter((k) => k.startsWith(STORAGE_PREFIX));
    const sessions: SessionMeta[] = [];
    for (const key of keys) {
      const sessionId = key.slice(STORAGE_PREFIX.length);
      const raw = localStorage.getItem(key);
      if (!raw) continue;
      try {
        const data = JSON.parse(raw) as AgentSessionState;
        sessions.push({
          sessionId: data.sessionId,
          title: data.title ?? '新会话',
          lastUpdated: data.lastUpdated ?? 0
        });
      } catch {
        continue;
      }
    }
    sessions.sort((a, b) => b.lastUpdated - a.lastUpdated);
    return sessions;
  },

  /** 切换当前活跃会话 */
  switchSession: (sessionId: string) => {
    const session = agentStateService.getSession(sessionId);
    if (session) localStorage.setItem(STORAGE_KEY_ACTIVE, sessionId);
  },

  /** 删除会话（需在删除后由调用方切换活跃会话） */
  deleteSession: (sessionId: string) => {
    localStorage.removeItem(STORAGE_PREFIX + sessionId);
    const active = localStorage.getItem(STORAGE_KEY_ACTIVE);
    if (active === sessionId) localStorage.removeItem(STORAGE_KEY_ACTIVE);
  },

  /** 更新会话标题（可由首条用户消息自动生成） */
  updateSessionTitle: (sessionId: string, title: string) => {
    agentStateService.saveSession(sessionId, { title });
  },

  getSession: (sessionId: string): AgentSessionState | null => {
    const raw = localStorage.getItem(STORAGE_PREFIX + sessionId);
    if (!raw) return null;
    try {
      return JSON.parse(raw);
    } catch (e) {
      return null;
    }
  },

  saveSession: (sessionId: string, updates: Partial<AgentSessionState>) => {
    const current = agentStateService.getSession(sessionId);
    if (!current) return;
    const updatedState = { ...current, ...updates, lastUpdated: Date.now() };
    localStorage.setItem(STORAGE_PREFIX + sessionId, JSON.stringify(updatedState));
  },

  /** 清空会话内容（保留会话，重置为初始状态） */
  clearSessionContent: (sessionId: string) => {
    const initialState: AgentSessionState = {
      sessionId,
      title: '新会话',
      geminiHistory: [],
      uiMessages: [],
      vfs: {
        'README.md': {
          path: 'README.md',
          content: '# Enterprise Agentic Project\n\nGenerated by Gemini 3 Supervisor.',
          language: 'markdown'
        }
      },
      knowledgeChunks: [],
      lastUpdated: Date.now()
    };
    localStorage.setItem(STORAGE_PREFIX + sessionId, JSON.stringify(initialState));
  },

  /** 删除会话（完全移除，兼容旧调用） */
  clearSession: (sessionId: string) => {
    agentStateService.deleteSession(sessionId);
  },

  updateVfs: (sessionId: string, path: string, content: string, language: string, isWriting?: boolean) => {
    const session = agentStateService.getSession(sessionId);
    if (!session) return;
    const newVfs = { ...session.vfs, [path]: { path, content, language, isWriting: isWriting ?? false } };
    agentStateService.saveSession(sessionId, { vfs: newVfs });
    window.dispatchEvent(new CustomEvent('vfs-updated', { detail: newVfs }));
  },

  clearSessionContext: (sessionId: string) => {
    const current = agentStateService.getSession(sessionId);
    if (!current || !current.geminiHistory) return;
    const cleanHistory = current.geminiHistory.map((msg: any) => {
      if (!msg.parts) return null;
      const textParts = msg.parts.filter((p: any) => p.text);
      if (textParts.length === 0) return null;
      return { role: msg.role, parts: textParts };
    }).filter(Boolean);
    agentStateService.saveSession(sessionId, { geminiHistory: cleanHistory });
  },

  syncUiState: (sessionId: string, messages: Message[]) => {
    agentStateService.saveSession(sessionId, { uiMessages: messages });
  },

  /** 获取当前活跃会话 ID */
  getActiveSessionId: (): string | null => localStorage.getItem(STORAGE_KEY_ACTIVE),

  /** 获取会话知识库分块 */
  getKnowledgeChunks: (sessionId: string): KnowledgeChunk[] => {
    const session = agentStateService.getSession(sessionId);
    return session?.knowledgeChunks ?? [];
  },

  /** 追加知识库分块到会话 */
  appendKnowledgeChunks: (sessionId: string, chunks: KnowledgeChunk[]): void => {
    const session = agentStateService.getSession(sessionId);
    if (!session) return;
    const existing = session.knowledgeChunks ?? [];
    agentStateService.saveSession(sessionId, { knowledgeChunks: [...existing, ...chunks] });
  },
};
